package com.myspace.ghtprocurementprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class deliveryNoteAuditList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.myspace.ghtprocurementprocess.deliveryNoteAudit> deliveryNote;

	public deliveryNoteAuditList() {
	}

	public java.util.List<com.myspace.ghtprocurementprocess.deliveryNoteAudit> getDeliveryNote() {
		return this.deliveryNote;
	}

	public void setDeliveryNote(
			java.util.List<com.myspace.ghtprocurementprocess.deliveryNoteAudit> deliveryNote) {
		this.deliveryNote = deliveryNote;
	}

	public deliveryNoteAuditList(
			java.util.List<com.myspace.ghtprocurementprocess.deliveryNoteAudit> deliveryNote) {
		this.deliveryNote = deliveryNote;
	}

}