package com.myspace.ghtprocurementprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class deliveryNoteAudit implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String dnNumber;
	private java.lang.String description;
	private java.util.Date dnDate;
	private java.lang.String poNumber;
	private java.util.Date poDate;
	private java.util.Date deliveryDate;
	private java.lang.String status;
	private java.lang.String remarks;

	public deliveryNoteAudit() {
	}

	public java.lang.String getDnNumber() {
		return this.dnNumber;
	}

	public void setDnNumber(java.lang.String dnNumber) {
		this.dnNumber = dnNumber;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.util.Date getDnDate() {
		return this.dnDate;
	}

	public void setDnDate(java.util.Date dnDate) {
		this.dnDate = dnDate;
	}

	public java.lang.String getPoNumber() {
		return this.poNumber;
	}

	public void setPoNumber(java.lang.String poNumber) {
		this.poNumber = poNumber;
	}

	public java.util.Date getPoDate() {
		return this.poDate;
	}

	public void setPoDate(java.util.Date poDate) {
		this.poDate = poDate;
	}

	public java.util.Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(java.util.Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(java.lang.String remarks) {
		this.remarks = remarks;
	}

	public deliveryNoteAudit(java.lang.String dnNumber,
			java.lang.String description, java.util.Date dnDate,
			java.lang.String poNumber, java.util.Date poDate,
			java.util.Date deliveryDate, java.lang.String status,
			java.lang.String remarks) {
		this.dnNumber = dnNumber;
		this.description = description;
		this.dnDate = dnDate;
		this.poNumber = poNumber;
		this.poDate = poDate;
		this.deliveryDate = deliveryDate;
		this.status = status;
		this.remarks = remarks;
	}

}