package com.myspace.ghtprocurementprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class itemInfoList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Item Information")
	private java.util.List<com.myspace.ghtprocurementprocess.ItemInformation> itemInformation;

	public itemInfoList() {
	}

	public java.util.List<com.myspace.ghtprocurementprocess.ItemInformation> getItemInformation() {
		return this.itemInformation;
	}

	public void setItemInformation(
			java.util.List<com.myspace.ghtprocurementprocess.ItemInformation> itemInformation) {
		this.itemInformation = itemInformation;
	}

	public itemInfoList(
			java.util.List<com.myspace.ghtprocurementprocess.ItemInformation> itemInformation) {
		this.itemInformation = itemInformation;
	}

}