package com.myspace.ghtprocurementprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ItemInformation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("itemCode")
	private java.lang.String itemCode;
	@org.kie.api.definition.type.Label("itemDescription")
	private java.lang.String itemDescription;
	@org.kie.api.definition.type.Label("unitCost")
	private Double unitCost;
	@org.kie.api.definition.type.Label("amount")
	private Double amount;

	private java.lang.Integer requiredQuanitity;

	private java.lang.Integer receiviedQuanitity;

	private java.util.Date requiredDate;

	private java.util.Date receivingDate;

	private String department;

	private java.lang.Integer availableStock;

	private java.lang.String units;

	@org.kie.api.definition.type.Label("Product")
	private java.lang.String product;

	@org.kie.api.definition.type.Label("Item Total")
	private java.lang.Double itemTotal;

	public ItemInformation() {
	}

	public java.lang.String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(java.lang.String itemCode) {
		this.itemCode = itemCode;
	}

	public java.lang.String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(java.lang.String itemDescription) {
		this.itemDescription = itemDescription;
	}

	public java.lang.Double getUnitCost() {
		return this.unitCost;
	}

	public void setUnitCost(java.lang.Double unitCost) {
		this.unitCost = unitCost;
	}

	public java.lang.Double getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Double amount) {
		this.amount = amount;
	}

	public java.lang.Integer getRequiredQuanitity() {
		return this.requiredQuanitity;
	}

	public void setRequiredQuanitity(java.lang.Integer requiredQuanitity) {
		this.requiredQuanitity = requiredQuanitity;
	}

	public java.lang.Integer getReceiviedQuanitity() {
		return this.receiviedQuanitity;
	}

	public void setReceiviedQuanitity(java.lang.Integer receiviedQuanitity) {
		this.receiviedQuanitity = receiviedQuanitity;
	}

	public java.util.Date getRequiredDate() {
		return this.requiredDate;
	}

	public void setRequiredDate(java.util.Date requiredDate) {
		this.requiredDate = requiredDate;
	}

	public java.util.Date getReceivingDate() {
		return this.receivingDate;
	}

	public void setReceivingDate(java.util.Date receivingDate) {
		this.receivingDate = receivingDate;
	}

	public java.lang.Integer getAvailableStock() {
		return this.availableStock;
	}

	public void setAvailableStock(java.lang.Integer availableStock) {
		this.availableStock = availableStock;
	}

	public java.lang.String getUnits() {
		return this.units;
	}

	public void setUnits(java.lang.String units) {
		this.units = units;
	}

	public java.lang.String getProduct() {
		return this.product;
	}

	public void setProduct(java.lang.String product) {
		this.product = product;
	}

	public java.lang.Double getItemTotal() {
		return this.itemTotal;
	}

	public void setItemTotal(java.lang.Double itemTotal) {
		this.itemTotal = itemTotal;
	}

	public java.lang.String getDepartment() {
		return this.department;
	}

	public void setDepartment(java.lang.String department) {
		this.department = department;
	}

	public ItemInformation(java.lang.String itemCode,
			java.lang.String itemDescription, java.lang.Double unitCost,
			java.lang.Double amount, java.lang.Integer requiredQuanitity,
			java.lang.Integer receiviedQuanitity, java.util.Date requiredDate,
			java.util.Date receivingDate, java.lang.String department,
			java.lang.Integer availableStock, java.lang.String units,
			java.lang.String product, java.lang.Double itemTotal) {
		this.itemCode = itemCode;
		this.itemDescription = itemDescription;
		this.unitCost = unitCost;
		this.amount = amount;
		this.requiredQuanitity = requiredQuanitity;
		this.receiviedQuanitity = receiviedQuanitity;
		this.requiredDate = requiredDate;
		this.receivingDate = receivingDate;
		this.department = department;
		this.availableStock = availableStock;
		this.units = units;
		this.product = product;
		this.itemTotal = itemTotal;
	}

}