package com.myspace.ghtprocurementprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("ItmReqObj")
public class ItmReqObj implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String refNumber;
	private java.lang.String description;
	private java.util.Date deliveryDate;
	private String country;
	private String department;
	private String branch;

	public ItmReqObj() {
	}

	public java.lang.String getRefNumber() {
		return this.refNumber;
	}

	public void setRefNumber(java.lang.String refNumber) {
		this.refNumber = refNumber;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.util.Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(java.util.Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	public java.lang.String getCountry() {
		return this.country;
	}

	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.lang.String getDepartment() {
		return this.department;
	}

	public void setDepartment(java.lang.String department) {
		this.department = department;
	}

	public java.lang.String getBranch() {
		return this.branch;
	}

	public void setBranch(java.lang.String branch) {
		this.branch = branch;
	}

	public ItmReqObj(java.lang.String refNumber, java.lang.String description,
			java.util.Date deliveryDate, java.lang.String country,
			java.lang.String department, java.lang.String branch) {
		this.refNumber = refNumber;
		this.description = description;
		this.deliveryDate = deliveryDate;
		this.country = country;
		this.department = department;
		this.branch = branch;
	}

}