package com.myspace.ghtprocurementprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class purchaseOrderIssue implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Double subTotal;
	private java.lang.Double discount;
	private java.lang.Double textableAmount;
	private java.lang.Double vat;
	private java.lang.Double total;

	public purchaseOrderIssue() {
	}

	public java.lang.Double getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(java.lang.Double subTotal) {
		this.subTotal = subTotal;
	}

	public java.lang.Double getDiscount() {
		return this.discount;
	}

	public void setDiscount(java.lang.Double discount) {
		this.discount = discount;
	}

	public java.lang.Double getTextableAmount() {
		return this.textableAmount;
	}

	public void setTextableAmount(java.lang.Double textableAmount) {
		this.textableAmount = textableAmount;
	}

	public java.lang.Double getVat() {
		return this.vat;
	}

	public void setVat(java.lang.Double vat) {
		this.vat = vat;
	}

	public java.lang.Double getTotal() {
		return this.total;
	}

	public void setTotal(java.lang.Double total) {
		this.total = total;
	}

	public purchaseOrderIssue(java.lang.Double subTotal,
			java.lang.Double discount, java.lang.Double textableAmount,
			java.lang.Double vat, java.lang.Double total) {
		this.subTotal = subTotal;
		this.discount = discount;
		this.textableAmount = textableAmount;
		this.vat = vat;
		this.total = total;
	}

}