package com.myspace.ghtprocurementprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class purchaseOrderAuditList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.myspace.ghtprocurementprocess.purchaseOrderAudit> purchaseOrderAudit;

	public purchaseOrderAuditList() {
	}

	public java.util.List<com.myspace.ghtprocurementprocess.purchaseOrderAudit> getPurchaseOrderAudit() {
		return this.purchaseOrderAudit;
	}

	public void setPurchaseOrderAudit(
			java.util.List<com.myspace.ghtprocurementprocess.purchaseOrderAudit> purchaseOrderAudit) {
		this.purchaseOrderAudit = purchaseOrderAudit;
	}

	public purchaseOrderAuditList(
			java.util.List<com.myspace.ghtprocurementprocess.purchaseOrderAudit> purchaseOrderAudit) {
		this.purchaseOrderAudit = purchaseOrderAudit;
	}

}