package com.myspace.ghtprocurementprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class purchaseOrder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("PO Number")
	private java.lang.String PONumber;

	@org.kie.api.definition.type.Label("Date")
	private java.util.Date date;

	@org.kie.api.definition.type.Label("Description")
	private java.lang.String description;

	@org.kie.api.definition.type.Label("Supplier")
	private java.lang.String supplier;

	@org.kie.api.definition.type.Label("Address")
	private java.lang.String address;

	@org.kie.api.definition.type.Label("Email")
	private java.lang.String email;

	@org.kie.api.definition.type.Label("Phone")
	private java.lang.String phone;

	@org.kie.api.definition.type.Label("Payment Term")
	private java.lang.String paymentTerm;

	@org.kie.api.definition.type.Label("Due Date")
	private java.util.Date dueDate;

	private Float availableBudget;

	private Float approvedBudget;

	private java.lang.String dnNumber;

	private java.util.Date dnDate;

	private java.util.Date deliveryDate;

	public purchaseOrder() {
	}

	public java.lang.String getPONumber() {
		return this.PONumber;
	}

	public void setPONumber(java.lang.String PONumber) {
		this.PONumber = PONumber;
	}

	public java.util.Date getDate() {
		return this.date;
	}

	public void setDate(java.util.Date date) {
		this.date = date;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getSupplier() {
		return this.supplier;
	}

	public void setSupplier(java.lang.String supplier) {
		this.supplier = supplier;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getPhone() {
		return this.phone;
	}

	public void setPhone(java.lang.String phone) {
		this.phone = phone;
	}

	public java.lang.String getPaymentTerm() {
		return this.paymentTerm;
	}

	public void setPaymentTerm(java.lang.String paymentTerm) {
		this.paymentTerm = paymentTerm;
	}

	public java.util.Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(java.util.Date dueDate) {
		this.dueDate = dueDate;
	}

	public java.lang.Float getAvailableBudget() {
		return this.availableBudget;
	}

	public void setAvailableBudget(java.lang.Float availableBudget) {
		this.availableBudget = availableBudget;
	}

	public java.lang.Float getApprovedBudget() {
		return this.approvedBudget;
	}

	public void setApprovedBudget(java.lang.Float approvedBudget) {
		this.approvedBudget = approvedBudget;
	}

	public java.lang.String getDnNumber() {
		return this.dnNumber;
	}

	public void setDnNumber(java.lang.String dnNumber) {
		this.dnNumber = dnNumber;
	}

	public java.util.Date getDnDate() {
		return this.dnDate;
	}

	public void setDnDate(java.util.Date dnDate) {
		this.dnDate = dnDate;
	}

	public java.util.Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(java.util.Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	public purchaseOrder(java.lang.String PONumber, java.util.Date date,
			java.lang.String description, java.lang.String supplier,
			java.lang.String address, java.lang.String email,
			java.lang.String phone, java.lang.String paymentTerm,
			java.util.Date dueDate, java.lang.Float availableBudget,
			java.lang.Float approvedBudget, java.lang.String dnNumber,
			java.util.Date dnDate, java.util.Date deliveryDate) {
		this.PONumber = PONumber;
		this.date = date;
		this.description = description;
		this.supplier = supplier;
		this.address = address;
		this.email = email;
		this.phone = phone;
		this.paymentTerm = paymentTerm;
		this.dueDate = dueDate;
		this.availableBudget = availableBudget;
		this.approvedBudget = approvedBudget;
		this.dnNumber = dnNumber;
		this.dnDate = dnDate;
		this.deliveryDate = deliveryDate;
	}

}