package com.myspace.ghtprocurementprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class purchaseOrderAudit implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "PO Number")
	private java.lang.String poNumber;
	@org.kie.api.definition.type.Label(value = "Description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label(value = "PO Date")
	private java.util.Date poDate;
	@org.kie.api.definition.type.Label(value = "PO Value")
	private java.lang.String poValue;
	@org.kie.api.definition.type.Label(value = "Delivery Date")
	private java.util.Date deliveryDate;
	@org.kie.api.definition.type.Label(value = "Status")
	private java.lang.String status;
	@org.kie.api.definition.type.Label(value = "Remarks")
	private java.lang.String remarks;

	public purchaseOrderAudit() {
	}

	public java.lang.String getPoNumber() {
		return this.poNumber;
	}

	public void setPoNumber(java.lang.String poNumber) {
		this.poNumber = poNumber;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.util.Date getPoDate() {
		return this.poDate;
	}

	public void setPoDate(java.util.Date poDate) {
		this.poDate = poDate;
	}

	public java.lang.String getPoValue() {
		return this.poValue;
	}

	public void setPoValue(java.lang.String poValue) {
		this.poValue = poValue;
	}

	public java.util.Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(java.util.Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(java.lang.String remarks) {
		this.remarks = remarks;
	}

	public purchaseOrderAudit(java.lang.String poNumber,
			java.lang.String description, java.util.Date poDate,
			java.lang.String poValue, java.util.Date deliveryDate,
			java.lang.String status, java.lang.String remarks) {
		this.poNumber = poNumber;
		this.description = description;
		this.poDate = poDate;
		this.poValue = poValue;
		this.deliveryDate = deliveryDate;
		this.status = status;
		this.remarks = remarks;
	}

}