package com.myspace.ghtprocurementprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class purchaseRequestAuditList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.myspace.ghtprocurementprocess.purchaseRequestAudit> purchaseRequestAudit;

	public purchaseRequestAuditList() {
	}

	public java.util.List<com.myspace.ghtprocurementprocess.purchaseRequestAudit> getPurchaseRequestAudit() {
		return this.purchaseRequestAudit;
	}

	public void setPurchaseRequestAudit(
			java.util.List<com.myspace.ghtprocurementprocess.purchaseRequestAudit> purchaseRequestAudit) {
		this.purchaseRequestAudit = purchaseRequestAudit;
	}

	public purchaseRequestAuditList(
			java.util.List<com.myspace.ghtprocurementprocess.purchaseRequestAudit> purchaseRequestAudit) {
		this.purchaseRequestAudit = purchaseRequestAudit;
	}

}