package com.myspace.ghtprocurementprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class purchaseRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("PR Number")
	private java.lang.String prNumber;
	@org.kie.api.definition.type.Label("Description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("PR Date")
	private java.util.Date prDate;

	@org.kie.api.definition.type.Label("Requester")
	private java.lang.String requester;

	@org.kie.api.definition.type.Label("Date Delivery")
	private java.util.Date dateDelivery;

	@org.kie.api.definition.type.Label("Country")
	private java.lang.String country;

	@org.kie.api.definition.type.Label("Department")
	private java.lang.String department;

	@org.kie.api.definition.type.Label("Branch")
	private java.lang.String branch;

	public purchaseRequest() {
	}

	public java.lang.String getPrNumber() {
		return this.prNumber;
	}

	public void setPrNumber(java.lang.String prNumber) {
		this.prNumber = prNumber;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.util.Date getPrDate() {
		return this.prDate;
	}

	public void setPrDate(java.util.Date prDate) {
		this.prDate = prDate;
	}

	public java.lang.String getRequester() {
		return this.requester;
	}

	public void setRequester(java.lang.String requester) {
		this.requester = requester;
	}

	public java.util.Date getDateDelivery() {
		return this.dateDelivery;
	}

	public void setDateDelivery(java.util.Date dateDelivery) {
		this.dateDelivery = dateDelivery;
	}

	public java.lang.String getCountry() {
		return this.country;
	}

	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.lang.String getDepartment() {
		return this.department;
	}

	public void setDepartment(java.lang.String department) {
		this.department = department;
	}

	public java.lang.String getBranch() {
		return this.branch;
	}

	public void setBranch(java.lang.String branch) {
		this.branch = branch;
	}

	public purchaseRequest(java.lang.String prNumber,
			java.lang.String description, java.util.Date prDate,
			java.lang.String requester, java.util.Date dateDelivery,
			java.lang.String country, java.lang.String department,
			java.lang.String branch) {
		this.prNumber = prNumber;
		this.description = description;
		this.prDate = prDate;
		this.requester = requester;
		this.dateDelivery = dateDelivery;
		this.country = country;
		this.department = department;
		this.branch = branch;
	}

}