package com.myspace.ghtprocurementprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class purchaseRequestAudit implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("PR Number")
	private java.lang.String PRNumber;
	@org.kie.api.definition.type.Label("Description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("Requester")
	private java.lang.String requester;
	@org.kie.api.definition.type.Label("Request Date")
	private java.util.Date requestDate;
	@org.kie.api.definition.type.Label("Delivery Date")
	private java.util.Date deliveryDate;
	@org.kie.api.definition.type.Label("Total Value")
	private java.lang.Double totalValue;
	@org.kie.api.definition.type.Label("Status")
	private java.lang.String status;
	@org.kie.api.definition.type.Label("Remarks")
	private java.lang.String remarks;

	public purchaseRequestAudit() {
	}

	public java.lang.String getPRNumber() {
		return this.PRNumber;
	}

	public void setPRNumber(java.lang.String PRNumber) {
		this.PRNumber = PRNumber;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getRequester() {
		return this.requester;
	}

	public void setRequester(java.lang.String requester) {
		this.requester = requester;
	}

	public java.util.Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(java.util.Date requestDate) {
		this.requestDate = requestDate;
	}

	public java.util.Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(java.util.Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	public java.lang.Double getTotalValue() {
		return this.totalValue;
	}

	public void setTotalValue(java.lang.Double totalValue) {
		this.totalValue = totalValue;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(java.lang.String remarks) {
		this.remarks = remarks;
	}

	public purchaseRequestAudit(java.lang.String PRNumber,
			java.lang.String description, java.lang.String requester,
			java.util.Date requestDate, java.util.Date deliveryDate,
			java.lang.Double totalValue, java.lang.String status,
			java.lang.String remarks) {
		this.PRNumber = PRNumber;
		this.description = description;
		this.requester = requester;
		this.requestDate = requestDate;
		this.deliveryDate = deliveryDate;
		this.totalValue = totalValue;
		this.status = status;
		this.remarks = remarks;
	}

}